### ISSUE TITLE
Gamja 주말 Todo List

### ISSUE THREAD

**Issue by leejk9592** [smart23033/boostcamp_iOS_bipeople#2]
# ~ 08. 06
- [x] Storyboard UI 구체화하기
- [x] Storyboard 쪼개서 쓰는 방법 공부하기
- [x] Realm, Chameleon, Naver iOS Map API ... 등 Open Source 공부하기
- [x] 다음 주일에 할 Todo List 작성해서 1주차 Readme.md로 작성해 오기

**Comment by leejk9592** [comment]
카멜레온 사용법은 공부하지 않았지만 Pass
