### ISSUE TITLE
3주차 Todo List

### ISSUE THREAD

**Issue by leejk9592** [smart23033/boostcamp_iOS_bipeople#65]
- [x] 앱 실행시, 서울 상공에서 현재 위치로 Zoom-in되는 애니메이션 추가
- [x] 사용자가 조절 가능한 줌 범위 설정
- [x] 검색창 UI 축소 해결
- [x] 경로 탐색 후 예상 거리/시간 표시
- [x] 경로이탈 취소 시, 취소가 되었음에도 경로가 맵에 표시되는 버그 수정
- [x] 네비게이션 모드에 여부에 관계없이 맵을 현재 위치로 고정(사용자가 맵을 사용할 경우 5초 가량 위치 고정 해제)
- [x] iOS 11 버전 미만에서, MarqueeLabel이 title view에서 보이지 않는 문제 해결
- [x] 기록 삭제 시, IndexPath 문제로 앱이 종료되는 현상 해결
- [x] 기록 저장 시, 도착지에 `설정 된 목적지`가 아닌 `현재 위치의 지명`으로 입력
- [x] 공공장소 바로안내
